[
   {
      "_id": 1,
      "title": "Michigan University",
      "avatar": "https://republika.mk/wp-content/uploads/2017/07/man-852762_960_720.jpg",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-07T09:30",
      "end": "2019-03-07T10:00",
      "type": "Appointment",
      "calendar": "Sales",
      "className": "colorAppointment",
      "username": "Caio Vitorelli",
      "backgroundColor": "#f4516c",
      "textColor": "#ffffff",
      "allDay": false
   },
   {
      "_id": 2,
      "title": "California Polytechnic",
      "avatar": "http://kidscoaching.com.br/wp-content/uploads/2016/08/opulent-profile-square-02.jpg",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-01T12:30",
      "end": "2019-03-01T15:30",
      "type": "Appointment",
      "calendar": "Sales",
      "className": "colorAppointment",
      "username": "Adam Rackham",
      "backgroundColor": "#9816f4",
      "textColor": "#ffffff",
      "allDay": false
   },
   {
      "_id": 3,
      "title": "Vermont University 2",
      "avatar": "http://kidscoaching.com.br/wp-content/uploads/2016/08/opulent-profile-square-02.jpg",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-02",
      "end": "2019-03-02",
      "type": "Check-in",
      "calendar": "Sales",
      "className": "colorCheck-in",
      "username": "Adam Rackham",
      "backgroundColor": "#9816f4",
      "textColor": "#ffffff",
      "allDay": true
   },
   {
      "_id": 4,
      "title": "Vermont University",
      "avatar": "",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-06",
      "end": "2019-03-06",
      "type": "Checkout",
      "calendar": "Sales",
      "className": "colorCheckout",
      "username": "Peter Grant",
      "backgroundColor": "#1756ff",
      "textColor": "#ffffff",
      "allDay": true
   },
   {
      "_id": 5,
      "title": "Michigan High School",
      "avatar": "",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-08",
      "end": "2019-03-08",
      "type": "Inventory",
      "calendar": "Lettings",
      "className": "colorInventory",
      "username": "Peter Grant",
      "backgroundColor": "#1756ff",
      "textColor": "#ffffff",
      "allDay": true
   },
   {
      "_id": 6,
      "title": "Vermont High School",
      "avatar": "",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-09",
      "end": "2019-03-09",
      "type": "Valuation",
      "calendar": "Lettings",
      "className": "colorValuation",
      "username": "Peter Grant",
      "backgroundColor": "#1756ff",
      "textColor": "#ffffff",
      "allDay": true
   },
   {
      "_id": 7,
      "title": "California High School",
      "avatar": "https://republika.mk/wp-content/uploads/2017/07/man-852762_960_720.jpg",
      "description": "Lorem ipsum dolor sit incid idunt ut Lorem ipsum sit.",
      "start": "2019-03-07",
      "end": "2019-03-08",
      "type": "Viewing",
      "calendar": "Lettings",
      "className": "colorViewing",
      "username": "Caio Vitorelli",
      "backgroundColor": "#f4516c",
      "textColor": "#ffffff",
      "allDay": true
   }
]